global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: rag-indexer
    metrics_path: /metrics
    static_configs:
      - targets: ["wikimedia-rag-indexer:9100"]

  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: kafka-exporter
    static_configs:
      - targets: ["kafka-exporter:9308"]

  - job_name: redpanda
    metrics_path: /metrics
    static_configs:
      - targets: ["wikimedia-redpanda:9644"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
